#!/bin/sh

### BEGIN INIT INFO
# Provides:             resize-helper
# Required-Start:       $local_fs
# Required-Stop:
# Default-Start:        S
# Default-Stop:
# Short-Description:  Resize the last partition
### END INIT INFO


case "$1" in
  start)
    reboot=false

    echo "Expanding last partition..."

    /usr/sbin/resize-helper

    retVal=$?
    if [ $retVal -ne 0 ]; then
        echo "Expanding partition has failed, see log files. Error code: $?"
    else
        echo "Expanding partition success"
    fi

    update-rc.d -f resize-last remove >/dev/null 2>&1

  ;;

  *)
    echo "Usage: $0 {start}" >&2
    exit 1
  ;;
esac

exit 0
