header:
    version: 9

# make the default rpi3
machine: raspberrypi3-64

distro: poky

target: xorg-dev-image

env:
    DL_DIR: "${HOME}/shared/downloads"
    SSTATE_DIR: "${HOME}/shared/oe/sstate-cache"
    PERSISTENT_DIR: "${HOME}/shared/oe-core"

repos:

    meta-small-arm-extra:
        #url: "https://github.com/sarnold/meta-small-arm-extra.git"
        path: "layers/meta-small-arm-extra"
        branch: kirkstone
        layers:
            .:

    poky:
        url: "https://git.yoctoproject.org/poky"
        branch: kirkstone
        path: "layers/poky"
        layers:
            meta:
            meta-poky:
            meta-yocto-bsp:

    meta-raspberrypi:
        url: "https://github.com/agherzan/meta-raspberrypi"
        branch: kirkstone
        path: "layers/meta-raspberrypi"

    meta-openembedded:
        url: http://git.openembedded.org/meta-openembedded
        branch: kirkstone
        path: "layers/meta-openembedded"
        layers:
            meta-oe:
            meta-python:
            meta-networking:

local_conf_header:
    base: |
        BBMASK = "meta-small-arm-extra/recipes-qt/"
        PACKAGE_CLASSES ?= "package_ipk"
        PATCHRESOLVE = "noop"
        IMAGE_FSTYPES:append = " wic.xz"
        CORE_IMAGE_EXTRA_INSTALL:append = " nano haveged"
        EXTRA_IMAGE_FEATURES:append = " ssh-server-openssh"
        EXTRA_IMAGE_FEATURES:append = " debug-tweaks"
        INHERIT:append = " uninative rm_work toaster"
        DISTRO_FEATURES:append = " largefile"
        PREFERRED_PROVIDER_virtual/kernel = "linux-raspberrypi"
        RPI_USE_U_BOOT = "1"
        DISPMANX_OFFLINE = "1"
        ENABLE_UART = "1"
