header:
    version: 9

# make the default rpi3
machine: raspberrypi3-64

distro: poky

target: xorg-dev-image

env:
    PACKAGE_FEED_IP_PORT: "192.168.7.150:8000"
    PACKAGE_FEED_TYPE: ipk

repos:

    meta-small-arm-extra:
        #url: "https://github.com/sarnold/meta-small-arm-extra.git"
        path: "layers/meta-small-arm-extra"
        branch: mickledore
        layers:
            .:

    meta-security:
        url: "https://git.yoctoproject.org/meta-security"
        branch: mickledore
        path: "layers/meta-security"

    meta-security-backports:
        url: "https://github.com/VCTLabs/meta-security-backports"
        branch: langdale
        path: "layers/meta-security-backports"

    poky:
        url: "https://git.yoctoproject.org/poky"
        branch: mickledore
        path: "layers/poky"
        layers:
            meta:
            meta-poky:
            meta-yocto-bsp:

    meta-raspberrypi:
        url: "https://github.com/agherzan/meta-raspberrypi"
        branch: mickledore
        path: "layers/meta-raspberrypi"

    meta-openembedded:
        url: http://git.openembedded.org/meta-openembedded
        branch: mickledore
        path: "layers/meta-openembedded"
        layers:
            meta-oe:
            meta-python:
            meta-networking:

local_conf_header:
    base: |
        BBMASK = "meta-small-arm-extra/recipes-qt/"
        PACKAGE_CLASSES ?= "package_${PACKAGE_FEED_TYPE}"
        PACKAGE_FEED_URIS ?= "http://${PACKAGE_FEED_IP_PORT}"
        PATCHRESOLVE = "noop"
        IMAGE_FSTYPES:append = " wic wic.xz"
        IMAGE_INSTALL:remove = "distro-feed-configs"
        CORE_IMAGE_EXTRA_INSTALL:append = " nano resize-rootfs"
        EXTRA_IMAGE_FEATURES:append = " package-management ssh-server-openssh"
        EXTRA_IMAGE_FEATURES:append = " debug-tweaks"
        INHERIT:append = " uninative"
        DISTRO_FEATURES:append = " largefile opengl pam"
        ROOT_HOME = "/root"
        ROOTLESS_X = "1"
    rpi-specific: |
        PREFERRED_PROVIDER_virtual/kernel = "linux-raspberrypi"
        DISPMANX_OFFLINE = "1"
