#@TYPE: Machine
#@NAME: bananapi-m1-plus
#@DESCRIPTION: Machine configuration for the bananapi-m1-plus, based on allwinner A20 CPU http://banana-pi.org/

require conf/machine/include/sun7i.inc

KERNEL_DEVICETREE = "allwinner/sun7i-a20-bananapi-m1-plus.dtb"
UBOOT_MACHINE = "bananapi_m1_plus_config"

MACHINE_ESSENTIAL_EXTRA_RDEPENDS += "\
    kernel-modules \
"

# support fitImage sp we can support signing
KERNEL_CLASSES += "kernel-fitimage"
KERNEL_IMAGETYPES += " fitImage "

IMAGE_BOOT_FILES:append = " fitImage;image.ub"
INITRAMFS_FSTYPES += "cpio.gz tar.gz"
IMAGE_FSTYPES += "ext4.gz"
IMAGE_FSTYPES:remove = "ext3 wic.gz"
