header:
    version: 9

distro: nodistro

target: console-dev-image

repos:
    meta-small-arm-extra:
        #url: "https://github.com/sarnold/meta-small-arm-extra.git"
        path: "layers/meta-small-arm-extra"
        branch: kirkstone
        layers:
            .:

    meta-security:
        url: "https://git.yoctoproject.org/meta-security"
        branch: kirkstone
        path: "layers/meta-security"

    meta-security-backports:
        url: "https://github.com/VCTLabs/meta-security-backports"
        branch: kirkstone
        path: "layers/meta-security-backports"
        layers:
            .:
            meta-hardening:

    meta-arm:
        url: "https://git.yoctoproject.org/meta-arm"
        branch: kirkstone
        path: "layers/meta-arm"
        layers:
            meta-arm:
            meta-arm-toolchain:

    bitbake:
        url: "https://git.openembedded.org/bitbake"
        tag: 2022-04.32-kirkstone
        path: "layers/bitbake"
        layers:
            .: disabled

    openembedded-core:
        url: "https://git.openembedded.org/openembedded-core"
        tag: 2022-04.32-kirkstone
        path: "layers/openembedded-core"
        layers:
            meta:

    meta-openembedded:
        url: http://git.openembedded.org/meta-openembedded
        branch: kirkstone
        path: "layers/meta-openembedded"
        layers:
            meta-oe:
            meta-python:
            meta-networking:
            meta-perl:

local_conf_header:
    base: |
        BBMASK = "meta-small-arm-extra/recipes-qt/"
        PACKAGE_CLASSES ?= "package_ipk"
        PATCHRESOLVE = "noop"
        IMAGE_FSTYPES:append = " wic.xz"
        CORE_IMAGE_EXTRA_INSTALL:append = " nano"
        IMAGE_FEATURES:append = " package-management ssh-server-openssh"
        require conf/distro/include/no-static-libs.inc
        require conf/distro/include/yocto-uninative.inc
        require conf/distro/include/security_flags.inc
        INHERIT:append = " uninative rm_work toaster"
        DISTRO_FEATURES:append = " seccomp"
        ROOT_HOME = "/root"
