header:
    version: 9

distro: nodistro

target: console-image-minimal

env:
    PACKAGE_FEED_IP_PORT: "192.168.7.150:8000"
    PACKAGE_FEED_TYPE: ipk

repos:
    meta-small-arm-extra:
        #url: "https://github.com/sarnold/meta-small-arm-extra.git"
        branch: mickledore
        path: "layers/meta-small-arm-extra"
        layers:
            .:

    meta-security:
        url: "https://git.yoctoproject.org/meta-security"
        branch: mickledore
        path: "layers/meta-security"

    meta-security-backports:
        url: "https://github.com/VCTLabs/meta-security-backports"
        branch: langdale
        path: "layers/meta-security-backports"

    bitbake:
        url: "https://git.openembedded.org/bitbake"
        tag: 2023-04.4-mickledore
        path: "layers/bitbake"
        layers:
            .: excluded

    openembedded-core:
        url: "https://git.openembedded.org/openembedded-core"
        tag: 2023-04.4-mickledore
        path: "layers/openembedded-core"
        layers:
            meta:
        patches:
            p1:
                repo: openembedded-core
                # this path starts with layers path from above
                path: ../meta-small-arm-extra/patches/0001-fix-replicate-jama-patch-for-libxcrypt-build-branch.patch

    meta-openembedded:
        url: http://git.openembedded.org/meta-openembedded
        branch: mickledore
        path: "layers/meta-openembedded"
        layers:
            meta-oe:
            meta-python:
            meta-networking:
            meta-perl:
        patches:
            p1:
                repo: meta-openembedded
                path: ../meta-small-arm-extra/patches/0001-fix-jack-backport-waf-python-patches-from-styhead.patch

local_conf_header:
    base: |
        PACKAGE_CLASSES ?= "package_${PACKAGE_FEED_TYPE}"
        PACKAGE_FEED_URIS ?= "http://${PACKAGE_FEED_IP_PORT}"
        PATCHRESOLVE = "noop"
        IMAGE_FSTYPES:append = " wic wic.xz"
        IMAGE_INSTALL:remove = "distro-feed-configs"
        CORE_IMAGE_EXTRA_INSTALL:append = " nano resize-rootfs"
        EXTRA_IMAGE_FEATURES:append = " package-management ssh-server-openssh"
        EXTRA_IMAGE_FEATURES:append = " debug-tweaks"
        require conf/distro/include/no-static-libs.inc
        require conf/distro/include/yocto-uninative.inc
        require conf/distro/include/security_flags.inc
        INHERIT:append = " uninative"
        DISTRO_FEATURES:append = " seccomp security"
        ROOT_HOME = "/root"
        BBMASK += "meta-small-arm-extra/recipes-qt/"
