header:
    version: 14

distro: nodistro

target: core-image-base

env:
    PACKAGE_FEED_IP_PORT: "192.168.7.150:8000"
    PACKAGE_FEED_TYPE: ipk

repos:
    meta-small-arm-extra:
        #url: "https://github.com/sarnold/meta-small-arm-extra.git"
        branch: scarthgap
        path: "layers/meta-small-arm-extra"
        layers:
            .:

    meta-security:
        url: "https://git.yoctoproject.org/meta-security"
        branch: scarthgap
        path: "layers/meta-security"

    meta-security-backports:
        url: "https://github.com/VCTLabs/meta-security-backports"
        branch: scarthgap
        path: "layers/meta-security-backports"

    bitbake:
        url: "https://git.openembedded.org/bitbake"
        tag: 2024-04.14-scarthgap
        path: "layers/bitbake"
        layers:
            .: disabled

    openembedded-core:
        url: "https://git.openembedded.org/openembedded-core"
        branch: scarthgap
        path: "layers/openembedded-core"
        layers:
            meta:

    meta-openembedded:
        url: "http://git.openembedded.org/meta-openembedded"
        branch: scarthgap
        path: "layers/meta-openembedded"
        layers:
            meta-oe:
            meta-python:
            meta-networking:
            meta-perl:

local_conf_header:
    base: |
        PACKAGE_CLASSES ?= "package_${PACKAGE_FEED_TYPE}"
        PACKAGE_FEED_URIS ?= "http://${PACKAGE_FEED_IP_PORT}"
        PATCHRESOLVE = "noop"
        IMAGE_FSTYPES:append = " wic wic.xz"
        IMAGE_INSTALL:remove = "distro-feed-configs"
        CORE_IMAGE_EXTRA_INSTALL:append = " nano resize-helper bash-completion-extra iproute2"
        EXTRA_IMAGE_FEATURES:append = " package-management ssh-server-openssh"
        EXTRA_IMAGE_FEATURES:append = " debug-tweaks tools-debug"
        require conf/distro/include/no-static-libs.inc
        require conf/distro/include/yocto-uninative.inc
        require conf/distro/include/security_flags.inc
        INHERIT:append = " uninative"
        DISTRO_FEATURES:append = " seccomp security"
        DISTRO_FEATURES:remove = "ld-is-gold nfc nfs 3g"
        ROOT_HOME = "/root"
        BBMASK += "meta-small-arm-extra/recipes-qt/"
