DESKTOP_APPS = " \
    imagemagick \
    gkrellm \
    vala-terminal \
    leafpad \
    leafpad-stock-icons \
    pcmanfm \
    xfmpc \
    geany \
    gnuplot-x11 \
    gst-meta-video \
    gst-meta-audio \
"

DEJAVU_FONTS = " \
    ttf-dejavu-sans \
    ttf-dejavu-sans-condensed \
    ttf-dejavu-sans-mono \
    ttf-dejavu-serif \
    ttf-dejavu-serif-condensed \
"

IMAGE_INSTALL += "\
    ${DESKTOP_APPS} \
    ${DEJAVU_FONTS} \
"

