#!/bin/sh
#
# This is an init script for openembedded
# Copy it to @SYSCONFDIR@/init.d/gkrellmd and type
# > update-rc.d gkrellmd defaults 60
#

PATH=/bin:/usr/bin:/sbin:/usr/sbin

case "$1" in
    start)
	echo -n "Starting system monitoring daemon: "
	start-stop-daemon -S -x /usr/sbin/gkrellmd
	if [ $? = 0 ]; then
	    echo "gkrellmd."
	else
	    echo "(failed.)"
	fi
	;;
    stop)
	echo -n "Stopping system monitoring daemon: "
	start-stop-daemon -K \
		-x /usr/sbin/gkrellmd
	echo "gkrellmd."
	;;
    restart|force-reload) 
	$0 stop
	$0 start
	exit
	;;
    *)
	echo "Usage: /etc/init.d/gkrellmd {start|stop|restart|force-reload}"
	exit 1
	;;
esac

exit 0
